### PR TITLE
SftpClient: support uploading file from Stream.

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/tmds/Tmds.Ssh/issues/267.

cc @yokrysty

### CODE REVIEW

**Comment by yokrysty** [comment]
oh yes i see, seems better you tackled the async writes which i didn't
for my use cases was enough

some questions:
i still don't understand the async usage on streams because you have await previousCopy.ConfigureAwait(false), so everything goes one after another (i also addressed this one in my pull request, but probably you didn't saw it)
i am thinking more like writing chunks at different offsets in parallel

in the method GetPermissionsForFile the Default has an additional & ~PretendUMask
which is skipped when having a Stream and i don't know what is doing, is it needed or not?
in my changes the reason i used the GetPermissionsForFile is because you had there implementation for Windows (which is currently not finished) and Linux

**Comment by tmds** [comment]
> i still don't understand the async usage on streams because you have await previousCopy.ConfigureAwait(false), so everything goes one after another (i also addressed this one in my pull request, but probably you didn't saw it)
i am thinking more like writing chunks at different offsets in parallel

 Here the `previousCopy.ConfigureAwait` happens at the end, so the writes are happening in parallel (when `pipelineSyncWrites`).

In the `!pipelineSyncWrites` case there is some room for optimization.

> in the method GetPermissionsForFile the Default has an additional & ~PretendUMask
which is skipped when having a Stream and i don't know what is doing, is it needed or not?

By lack of information `GetPermissionsForFile` assumes files on Windows aren't writable for 'other'.
Note that when the file/directory is created on the server, it will also apply a [umask](https://man7.org/linux/man-pages/man1/umask.1p.html) that filters out permission. Normally, it will filter out the 'other write' permission (and often also the 'group write' permission).

**Comment by yokrysty** [comment]
still in don't understand how it's not everything messed up at the destination without knowing the offset where to write
but i think because you await CopyToAsync for upload and await WriteAsync for download is doing everything in order

**Comment by tmds** [comment]
> how it's not everything messed up at the destination

In the `!pipelineSyncWrites` case, CopyToAsync does serial writing.
In the `pipelineSyncWrites` case, each `CopyBuffer` works on a specific `offset`. The SFTP SSH write operation will write specifically at that offset.

**Pull request merged**
