### PR TITLE
Tests: Dockerfile: use centos:stream10-development.

### PR DESCRIPTION
**Pull request by tmds**

### CODE REVIEW

**Comment by tmds** [comment]
@Jakuje @jborean93

With debug3 this interesting line shows up in the log:

```
debug3: PAM: do_pam_account pam_acct_mgmt = 9 (Authentication service cannot retrieve authentication info)
```

Larger section of the log:
```
debug1: do_pam_account: called
debug2: do_pam_account: auth information in SSH_AUTH_INFO_0
debug3: PAM: do_pam_account pam_acct_mgmt = 9 (Authentication service cannot retrieve authentication info)
debug3: mm_request_send: entering, type 103
Failed publickey for testuser from 10.0.2.100 port 39110 ssh2: RSA SHA256:zxjEf8ywcbncdGEflP4PXxrOp8YxAO/2WBL/Rq/+k5w
debug1: auth_activate_options: setting new authentication options [preauth]
debug2: userauth_pubkey: authenticated 1 pkalg rsa-sha2-512 [preauth]
debug3: user_specific_delay: user specific delay 0.000ms [preauth]
debug3: ensure_minimum_time_since: elapsed 5.811ms, delaying 2.824ms (requested 8.635ms) [preauth]
debug3: mm_do_pam_account entering [preauth]
debug3: mm_request_send: entering, type 102 [preauth]
debug3: mm_request_receive_expect: entering, type 103 [preauth]
debug3: mm_request_receive: entering [preauth]
debug3: mm_do_pam_account returning 0 [preauth]
Access denied for user testuser by PAM account configuration [preauth]
debug1: do_cleanup [preauth]
debug3: PAM: sshpam_thread_cleanup entering [preauth]
debug1: monitor_read_log: child log fd closed
debug3: mm_request_receive: entering
debug3: mm_request_receive: monitor fd closed
debug1: mm_reap: preauth child exited with status 255
debug1: do_cleanup
debug1: PAM: cleanup
debug3: PAM: sshpam_thread_cleanup entering
```

I'm going to try to disable PAM now, and see what that gives.

**Comment by tmds** [comment]
@Jakuje @jborean93 these are the findings:

- With `UsePAM no` things are working. OpenSSH does print a message:
```
WARNING: 'UsePAM no' is not supported in this build and may cause several problems
```
As mentioned in the previous comment, with PAM enabled this shows up in the log:
```
debug3: PAM: do_pam_account pam_acct_mgmt = 9 (Authentication service cannot retrieve authentication info)
```

- Newer versions of OpenSSH do some tracking per source IP address of failed auth attempts and penalize those addresses. As the test include some failed auth attempts, this caused other tests to fail. I've addressed this by adding a `PerSourcePenaltyExemptList`.

- The only remaining failing tests is now the Kerberos test that use the Kerberos credential username as the ssh auth username. Auth is failing as shown below. Also locally these tests fail when `UsePAM no` is set.

```
debug1: userauth-request for user testuser@REALM.TEST service ssh-connection method gssapi-with-mic [preauth]
debug1: attempt 0 failures 0 [preauth]
debug3: mm_getpwnamallow: entering [preauth]
debug3: mm_request_send: entering, type 8 [preauth]
debug3: mm_getpwnamallow: waiting for MONITOR_ANS_PWNAM [preauth]
debug3: mm_request_receive_expect: entering, type 9 [preauth]
debug3: mm_request_receive: entering [preauth]
debug3: mm_request_receive: entering
debug3: monitor_read: checking request 8
debug3: mm_answer_pwnamallow: entering
debug2: parse_server_config_depth: config reprocess config len 3712
debug2: parse_server_config_depth: config /etc/ssh/sshd_config.d/40-redhat-crypto-policies.conf len 413
debug2: parse_server_config_depth: config /etc/crypto-policies/back-ends/opensshserver.config len 2297
debug2: parse_server_config_depth: config /etc/ssh/sshd_config.d/50-redhat.conf len 307
debug2: parse_server_config_depth: config /etc/ssh/sshd_config.d/90-gssapi.conf len 54
debug2: parse_server_config_depth: config /etc/ssh/sshd_config.d/99-no-per-source-penalty.conf len 45
debug3: auth_shadow_acctexpired: today 20019 sp_expire -1 days left -20020
debug3: account expiration disabled
User testuser@REALM.TEST not allowed because account is locked
```

Do you have some thoughts on what may be needed to make `UsePAM yes` work?

**Comment by jborean93** [comment]
Potentially you need to set a password (any password) for the `testuser@REALM.TEST` user that we add. Maybe PAM thinks the user is locked unless this is done.

**Comment by tmds** [comment]
> Potentially you need to set a password (any password) for the testuser@REALM.TEST user that we add. Maybe PAM thinks the user is locked unless this is done.

The test does work when I run it locally with the default of `UsePAM yes`. Also, if we're adding things for the Kerberos username I'm not sure if we maintain the difference between `useLocalUser` `true` and `false`.

I'm going to take the PR in its current form.

Thanks for your inputs @Jakuje and @jborean93, they were very helpful!

If you have some more suggestions to make `UsePAM yes` work, or to make the Kerberos useLocalUser=false work, I can try them. You can also try them local and/or open a PR and see what the CI makes of it.

**Pull request merged**
